from fpdf import FPDF
import datetime

class FinancialReportPDF(FPDF):
    def header(self):
        # Draw a beautiful dark header
        self.set_fill_color(26, 36, 43) # Sleek Dark Slate
        self.rect(0, 0, 210, 40, 'F')
        
        self.set_font('Helvetica', 'B', 20)
        self.set_text_color(255, 255, 255)
        self.cell(0, 10, 'ZENITH CA', ln=True, align='L')
        self.set_font('Helvetica', 'I', 10)
        self.set_text_color(180, 200, 210)
        self.cell(0, 5, 'Autonomous Artificial Intelligence Chartered Accountant & Tax Advisor', ln=True, align='L')
        self.ln(20)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Zenith CA on {datetime.date.today().strftime("%d-%B-%Y")} | Strictly Confidential', align='C')

def generate_financial_pdf(financials, tax_data, audit_findings, business_type):
    pdf = FinancialReportPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    
    # Report Title
    pdf.set_font('Helvetica', 'B', 16)
    pdf.set_text_color(26, 36, 43)
    pdf.cell(0, 10, 'COMPREHENSIVE AUDIT & FINANCIAL STATEMENT REPORT', ln=True)
    pdf.set_draw_color(46, 204, 113) # Emerald Green line
    pdf.set_linewidth(1)
    pdf.line(10, 52, 200, 52)
    pdf.ln(8)
    
    # Metadata Table
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(50, 50, 50)
    pdf.cell(100, 6, f"Entity Type: {business_type}", ln=False)
    pdf.cell(90, 6, f"Financial Period: Last 12 Months", ln=True, align='R')
    pdf.cell(100, 6, "Currency: INR (Rs.)", ln=False)
    pdf.cell(90, 6, f"Report Hash: SECURE-AI-CA-{datetime.datetime.now().strftime('%Y%M%S')}", ln=True, align='R')
    pdf.ln(5)
    
    # Executive Summary (Cards)
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_text_color(26, 36, 43)
    pdf.cell(0, 10, '1. Executive Summary', ln=True)
    
    pdf.set_font('Helvetica', '', 10)
    # Draw KPI Cards
    # Revenue Box
    pdf.set_fill_color(240, 248, 255)
    pdf.rect(10, 80, 58, 25, 'F')
    pdf.set_xy(10, 82)
    pdf.set_font('Helvetica', 'B', 8)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(58, 4, 'TOTAL REVENUE', ln=True, align='C')
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_text_color(46, 204, 113)
    pdf.cell(58, 8, f"Rs. {financials['Total_Revenue']:,.2f}", ln=True, align='C')
    
    # Expense Box
    pdf.set_xy(73, 82)
    pdf.set_font('Helvetica', 'B', 8)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(58, 4, 'TOTAL EXPENSES', ln=True, align='C')
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_text_color(231, 76, 60)
    pdf.cell(58, 8, f"Rs. {financials['Total_Expenses']:,.2f}", ln=True, align='C')
    
    # Net Income Box
    pdf.set_xy(136, 82)
    pdf.set_font('Helvetica', 'B', 8)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(58, 4, 'NET PROFIT', ln=True, align='C')
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_text_color(41, 128, 185)
    pdf.cell(58, 8, f"Rs. {financials['Net_Income']:,.2f}", ln=True, align='C')
    
    pdf.set_xy(10, 110)
    pdf.ln(5)
    
    # Section 2: P&L Statement
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_text_color(26, 36, 43)
    pdf.cell(0, 10, '2. Profit & Loss Statement (P&L Breakdown)', ln=True)
    
    # Table Header
    pdf.set_font('Helvetica', 'B', 10)
    pdf.set_fill_color(26, 36, 43)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(110, 8, 'Category Name', border=1, fill=True)
    pdf.cell(80, 8, 'Amount (Rs.)', border=1, fill=True, align='R')
    pdf.ln()
    
    # Table Rows
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(50, 50, 50)
    # Revenue Row
    pdf.set_fill_color(245, 245, 245)
    pdf.cell(110, 8, 'Operating Revenue (Sales & Subscriptions)', border=1, fill=True)
    pdf.cell(80, 8, f"Rs. {financials['Total_Revenue']:,.2f}", border=1, fill=True, align='R')
    pdf.ln()
    
    # Expenses Row
    for idx, row in financials['Category_Breakdown'].iterrows():
        pdf.cell(110, 8, str(row['Category']), border=1)
        pdf.cell(80, 8, f"Rs. {row['Amount']:,.2f}", border=1, align='R')
        pdf.ln()
        
    # Total Expenses Row
    pdf.set_font('Helvetica', 'B', 10)
    pdf.set_fill_color(245, 245, 245)
    pdf.cell(110, 8, 'Total Operating Expenses', border=1, fill=True)
    pdf.cell(80, 8, f"Rs. {financials['Total_Expenses']:,.2f}", border=1, fill=True, align='R')
    pdf.ln()
    
    # Net Profit Row
    pdf.set_fill_color(230, 245, 235)
    pdf.cell(110, 8, 'Net Profit before Taxes', border=1, fill=True)
    pdf.cell(80, 8, f"Rs. {financials['Net_Income']:,.2f}", border=1, fill=True, align='R')
    pdf.ln(12)
    
    # Section 3: Balance Sheet
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_text_color(26, 36, 43)
    pdf.cell(0, 10, '3. Simplified Balance Sheet Projection', ln=True)
    
    # Assets Header
    pdf.set_font('Helvetica', 'B', 10)
    pdf.set_fill_color(41, 128, 185)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(190, 8, 'ASSETS (What the Business Owns)', border=1, fill=True)
    pdf.ln()
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(50, 50, 50)
    for asset_name, asset_val in financials['Balance_Sheet']['Assets'].items():
        if asset_name == "Total Assets":
            pdf.set_font('Helvetica', 'B', 10)
            pdf.cell(110, 8, asset_name, border=1)
            pdf.cell(80, 8, f"Rs. {asset_val:,.2f}", border=1, align='R')
        else:
            pdf.set_font('Helvetica', '', 10)
            pdf.cell(110, 8, f"  {asset_name}", border=1)
            pdf.cell(80, 8, f"Rs. {asset_val:,.2f}", border=1, align='R')
        pdf.ln()
        
    pdf.ln(3)
    
    # Liabilities & Equity Header
    pdf.set_font('Helvetica', 'B', 10)
    pdf.set_fill_color(127, 140, 141)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(190, 8, 'LIABILITIES & EQUITY (How it is Funded)', border=1, fill=True)
    pdf.ln()
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(50, 50, 50)
    
    # Liabilities
    for liab_name, liab_val in financials['Balance_Sheet']['Liabilities'].items():
        if liab_name == "Total Liabilities":
            pdf.set_font('Helvetica', 'B', 10)
            pdf.cell(110, 8, liab_name, border=1)
            pdf.cell(80, 8, f"Rs. {liab_val:,.2f}", border=1, align='R')
        else:
            pdf.set_font('Helvetica', '', 10)
            pdf.cell(110, 8, f"  {liab_name}", border=1)
            pdf.cell(80, 8, f"Rs. {liab_val:,.2f}", border=1, align='R')
        pdf.ln()
        
    # Equity
    for eq_name, eq_val in financials['Balance_Sheet']['Equity'].items():
        if eq_name == "Total Equity":
            pdf.set_font('Helvetica', 'B', 10)
            pdf.cell(110, 8, eq_name, border=1)
            pdf.cell(80, 8, f"Rs. {eq_val:,.2f}", border=1, align='R')
        else:
            pdf.set_font('Helvetica', '', 10)
            pdf.cell(110, 8, f"  {eq_name}", border=1)
            pdf.cell(80, 8, f"Rs. {eq_val:,.2f}", border=1, align='R')
        pdf.ln()
        
    pdf.add_page()
    
    # Section 4: Taxation & Compliance
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_text_color(26, 36, 43)
    pdf.cell(0, 10, '4. Tax Assessment & GST Compliance', ln=True)
    pdf.set_draw_color(41, 128, 185)
    pdf.line(10, 22, 200, 22)
    pdf.ln(5)
    
    # GST Table
    pdf.set_font('Helvetica', 'B', 10)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(110, 8, 'GST Metric (18% Baseline)', border=1, fill=True)
    pdf.cell(80, 8, 'Value (Rs.)', border=1, fill=True, align='R')
    pdf.ln()
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(110, 8, 'GST Collected on Sales (Output GST)', border=1)
    pdf.cell(80, 8, f"Rs. {tax_data['Output_GST']:,.2f}", border=1, align='R')
    pdf.ln()
    pdf.cell(110, 8, 'GST Input Tax Credit Eligible (Input GST)', border=1)
    pdf.cell(80, 8, f"Rs. {tax_data['Input_GST_ITC']:,.2f}", border=1, align='R')
    pdf.ln()
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(110, 8, 'Net GST Payable to Government', border=1)
    pdf.cell(80, 8, f"Rs. {tax_data['Net_GST_Payable']:,.2f}", border=1, align='R')
    pdf.ln(12)
    
    # Income Tax Details
    pdf.set_font('Helvetica', 'B', 11)
    pdf.cell(0, 8, f"Income Tax Computation ({business_type})", ln=True)
    pdf.set_font('Helvetica', '', 10)
    
    tax_info = tax_data['Income_Tax']
    for k, v in tax_info.items():
        if k == "Slab Breakdown":
            continue
        pdf.cell(90, 8, f"  {k}:", border=1)
        if isinstance(v, (int, float)):
            pdf.cell(100, 8, f"Rs. {v:,.2f}", border=1, align='R')
        else:
            pdf.cell(100, 8, str(v), border=1, align='R')
        pdf.ln()
        
    pdf.ln(8)
    
    # Section 5: AI Audit Findings
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_text_color(26, 36, 43)
    pdf.cell(0, 10, '5. AI Transaction Audit Logs & Risk Assessment', ln=True)
    
    if len(audit_findings) == 0:
        pdf.set_font('Helvetica', 'I', 10)
        pdf.set_text_color(46, 204, 113)
        pdf.cell(0, 8, 'Clean Audit: No anomalies or suspicious transactions detected in the general ledger.', ln=True)
    else:
        pdf.set_font('Helvetica', 'B', 9)
        pdf.set_fill_color(26, 36, 43)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(20, 8, 'Severity', border=1, fill=True)
        pdf.cell(50, 8, 'Category', border=1, fill=True)
        pdf.cell(20, 8, 'Amount', border=1, fill=True, align='R')
        pdf.cell(100, 8, 'Auditor Flags / Remarks', border=1, fill=True)
        pdf.ln()
        
        pdf.set_font('Helvetica', '', 8.5)
        pdf.set_text_color(50, 50, 50)
        
        # Max out audit list to not overflow PDF (limit to 12 items)
        for idx, row in audit_findings.head(12).iterrows():
            severity = str(row['Severity'])
            if severity == "High":
                pdf.set_fill_color(254, 237, 238) # Light red
                pdf.set_text_color(186, 12, 47) # Red text
            elif severity == "Medium":
                pdf.set_fill_color(255, 249, 230) # Light yellow
                pdf.set_text_color(125, 95, 0) # Brown/Orange text
            else:
                pdf.set_fill_color(255, 255, 255)
                pdf.set_text_color(50, 50, 50)
                
            pdf.cell(20, 8, severity, border=1, fill=True)
            
            # Reset color for description
            pdf.set_text_color(50, 50, 50)
            pdf.cell(50, 8, str(row['Category'])[:25], border=1, fill=True)
            pdf.cell(20, 8, f"Rs.{row['Amount']:,.0f}", border=1, fill=True, align='R')
            pdf.cell(100, 8, str(row['Remarks'])[:60], border=1, fill=True)
            pdf.ln()
            
    # Disclaimer
    pdf.ln(10)
    pdf.set_font('Helvetica', 'I', 8)
    pdf.set_text_color(120, 120, 120)
    pdf.multi_cell(0, 4, "Zenith CA is an artificial intelligence financial advisor and does not constitute formal legal or certified public accounting services. Please consult local statutory guidance for official filings.")
    
    return pdf.output()
